### PR TITLE
Do not throw exception when no entries, just log it.

### PR DESCRIPTION
**Pull request by AdamVyborny**
https://keboola.atlassian.net/browse/COM-1132

### CODE REVIEW

**Comment by AdamVyborny** [comment]
@ondrajodas nevím úplně jak to pokrýt testem, upload fixtures neumí prázdné CSV...

**Comment by ondrajodas** [comment]
> upload fixtures neumí prázdné CSV

co to je za skript? nejde upravit?

**Comment by AdamVyborny** [comment]
> > upload fixtures neumí prázdné CSV
> 
> co to je za skript? nejde upravit?

`GuzzleHttp\Exception\ClientException: Client error: `POST https://connection.eu-central-1.keboola.com/v2/storage/buckets/in.c-test-wr-db-synapse/tables` resulted in a `400 Bad Request` response:
{"error":"Imported file cannot be empty","exceptionId":"connection-c53c6f58f3acd71755a111a3725583d4","code":"storage.tab (truncated...)`

**Comment by ondrajodas** [comment]
> > > upload fixtures neumí prázdné CSV
> > 
> > 
> > co to je za skript? nejde upravit?
> 
> `GuzzleHttp\Exception\ClientException: Client error: `POST [https://connection.eu-central-1.keboola.com/v2/storage/buckets/in.c-test-wr-db-synapse/tables`](https://connection.eu-central-1.keboola.com/v2/storage/buckets/in.c-test-wr-db-synapse/tables%60) resulted in a `400 Bad Request` response: {"error":"Imported file cannot be empty","exceptionId":"connection-c53c6f58f3acd71755a111a3725583d4","code":"storage.tab (truncated...)`

to je ze storage klienta? kde se to pouští?

**Comment by AdamVyborny** [comment]
@ondrajodas ano, ze storage clienta:
`/code/vendor/keboola/storage-api-client/src/Keboola/StorageApi/Client.php:2141
/code/vendor/keboola/storage-api-client/src/Keboola/StorageApi/Client.php:2057
/code/vendor/keboola/storage-api-client/src/Keboola/StorageApi/Client.php:575
/code/src/Test/StagingStorageLoader.php:70
/code/tests/functional/DatadirTest.php:102
/code/tests/functional/DatadirTest.php:72
/code/vendor/keboola/datadir-tests/src/DatadirTestCase.php:16
`

**Pull request merged**
